services:

  back:
    container_name: restaurant-api
    build:
      context: .
    ports:
      - "8001:80"
    restart: unless-stopped
    environment:
      - DATABASE_URL=mysql://Amelie:Ag1805Sz0602@@db:3307/restaurantQuaiAntique
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: Ag1805Sz0602@
      MYSQL_DATABASE: restaurantQuaiAntique
      MYSQL_USER: Amelie
      MYSQL_PASSWORD: Ag1805Sz0602@
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2.2
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: Amelie
      PMA_PASSWORD: Ag1805Sz0602@
    ports:
      - "8081:80"

volumes:
  db_data:
